### ISSUE TITLE
External profiles followed by local users show no statuses

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#145]
Currently, when an external profile is followed by a local user, its content appears empty—none of its statuses are initially visible. A helpful feature is the link that allows users to view the statuses on the profile’s original server. This behavior is similar to how Mastodon and Pixelfed servers function.

However, a more user-friendly option would be to include a button that allows users to fetch statuses (along with reactions and comments) to the local server on demand. This would synchronize the external profile with its local copy, making it easier to engage with content directly from the local instance.

This issue has been described in detail at the following link:

https://github.com/w3c/activitypub/issues/450

**Comment by mczachurski** [comment]
This is certainly a functionality worth considering 🤔. 

I assume that retrieving statuses would be feasible; however, obtaining comments and likes seems unlikely. These elements are typically not retrievable directly through the ActivityPub API. Another challenge would be maintaining the correct order of statuses. It is not possible to „insert” a new status into an arbitrary position in the database. Status IDs are generated according to the ‘snowflake’ algorithm and are sorted based on their ID numbers.

**Comment by mgrzeca** [comment]
Actually, the first 41 most significant bits of a Snowflake ID represent a timestamp, which means you can substitute it with a past date from the status being retrieved from the remote server. This should solve the issue of inserting a status into any arbitrary position in the database.

Unless we're thinking about different Snowflake algorithms, the one commonly referred to as Snowflake ID should address the challenge of placing statuses in the correct order.

**Comment by mczachurski** [comment]
Yes. But we can try to download statues as "unlisted". Thus they will appear on local timeline but not on the user's timelines. Still not perfect but I don't have other ideas for now.
